### ISSUE TITLE
simpler handling of .env

### ISSUE THREAD

**Issue by snoyes** [aalcala07/home_dashboard#10]
TIL: Instead of a .env.example that you have to copy to .env, you can just make .env what is currently .env.example, and then `git update-index --skip-worktree .env`, which causes git to ignore it. Then you can make your own private changes, and they won't get posted to github.

**Comment by aalcala07** [comment]
Didn't know that. 

I don't think we'd actually need that because we would still want the example config in the repository and `.env` would be ignored either way.

**Comment by snoyes** [comment]
It seems like I don't really have a good handle on how it works anyway - I tried it with a different file, and it seemed to get in the way of checking out different branches; wouldn't merge because it would stomp on an untracked file.
